# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the source-code branch
  push:
    branches: [ source-code ]
  pull_request:
    branches: [ source-code ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      - name: Install blogdown
        run: |
          R -e 'install.packages("blogdown")'
      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo(version = "0.80.0")'
      - name: Build site
        run: |
          R -e 'blogdown::build_site(TRUE)'
      - name: Fetch Main 
        uses: actions/checkout@v2
        with: 
          ref: 'main'
          path: 'main/'
      - name: Deploy to github 
        run: |
          cd main
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git rm -rf .
          rsync -avz  ../public/ .
          git add .
          git commit -m "update website"
          git push --force origin main
